@customerToken = 672e3c19-9872-4bc6-9c2d-c435f15a78d9
@adminToken = 7921c133-07a6-475b-9d1b-ae17ef0904f8
@carToken = 4096e4ce-f926-4b10-b5c0-70845f3e861e

### Signup
POST http://localhost:8080/api/signup
Content-Type: application/json

{"firstname":"Katharina","lastname":"lul","age":23,"username":"Kathi123","password":"1234","creditCardNr":"1111","driversLicenceNr":"A123"}

### Login Kunde
POST http://localhost:8080/api/session/login
Authorization: Basic Kathi123 1234

### Login Admin
POST http://localhost:8080/api/session/login
Authorization: Basic admin admin123

### Driver-Liste
GET http://localhost:8080/api/drivers
Authorization: {{customerToken}}

### Eigenes Profil ändern
PUT http://localhost:8080/api/drivers/6
Authorization: {{customerToken}}
Content-Type: application/json

{"age":420, "firstname": "Catlyn"}

### Logout
POST http://localhost:8080/api/session/logout
Authorization: {{customerToken}}

### Auto anlegen
POST http://localhost:8080/api/cars
Authorization: {{adminToken}}
Content-Type: application/json

{"carName":"Auto 1","description":"böB Auto","coordinates":{"latitude":42.0,"longitude":18.7}}

### Alle Autos
GET http://localhost:8080/api/cars
Authorization: {{adminToken}}

### Ein Auto
GET http://localhost:8080/api/cars/7
Authorization: {{adminToken}}

### Auto ändern
PATCH http://localhost:8080/api/car/6
Authorization: {{adminToken}}
Content-Type: application/json

{"carName":"Auto 3"}

### Auto löschen
DELETE http://localhost:8080/api/car/2
Authorization: {{adminToken}}

### Status
POST http://localhost:8080/api/cars/7/status
Authorization: {{carToken}}
Content-Type: application/json

{"currentUser":"Catlyn","coordinates":{"latitude":48.2,"longitude":16.3},"time":"2026-09-20T10:00:59","status":"OCCUPIED","kilometer":1.5,"duration":60}

### Alarm
POST http://localhost:8080/api/cars/7/alarm
Authorization: {{carToken}}
Content-Type: application/json

{"statusUpdate":{"currentUser":"max","coordinates":{"latitude":48.2,"longitude":16.3},"time":"2026-09-20T10:00:00","status":"OCCUPIED","kilometer":0.0,"duration":60},"priority":"HIGH","description":"Unfall"}

### Report Gen
POST http://localhost:8080/api/reports/6
Authorization: {{adminToken}}


// docker exec -it carsharing-db psql -U postgres -d carsharing -c "SELECT id, username, user_role, token FROM list_user;"